const state={snapshot:null,fx:null,history:null,target:'USD',byCode:new Map(),world:null};
const numericToAlpha2=new Map(Object.entries({'036':'AU','040':'AT','048':'BH','051':'AM','056':'BE','070':'BA','076':'BR','100':'BG','124':'CA','144':'LK','152':'CL','158':'TW','170':'CO','188':'CR','191':'HR','196':'CY','203':'CZ','208':'DK','214':'DO','218':'EC','233':'EE','246':'FI','250':'FR','268':'GE','276':'DE','288':'GH','300':'GR','320':'GT','344':'HK','348':'HU','352':'IS','360':'ID','372':'IE','376':'IL','380':'IT','388':'JM','392':'JP','398':'KZ','400':'JO','404':'KE','410':'KR','422':'LB','428':'LV','442':'LU','458':'MY','470':'MT','480':'MU','484':'MX','498':'MD','524':'NP','528':'NL','554':'NZ','558':'NI','578':'NO','591':'PA','600':'PY','604':'PE','608':'PH','616':'PL','620':'PT','642':'RO','646':'RW','688':'RS','702':'SG','703':'SK','705':'SI','710':'ZA','724':'ES','752':'SE','756':'CH','764':'TH','780':'TT','784':'AE','800':'UG','826':'GB','840':'US','858':'UY','704':'VN','894':'ZM'}));
const fmt=new Intl.NumberFormat(undefined,{maximumFractionDigits:2});
const syms={USD:'$',JPY:'¥',EUR:'€',GBP:'£'};
async function j(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
function cv(v,from,to){if(from===to)return v;const R=state.fx?.rates||{},a=from==='USD'?1:Number(R[from]),b=to==='USD'?1:Number(R[to]);return Number.isFinite(a)&&a>0&&Number.isFinite(b)&&b>0?(v/a)*b:null}
function dp(r){return cv(r.pricePer330Ml,r.currency,state.target)}
function money(v,c=state.target){return v==null?'FX unavailable':`${syms[c]||c+' '}${fmt.format(v)}`}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function summary(records){document.querySelector('#fresh-count').textContent=state.snapshot.freshCountryCount;document.querySelector('#gate').textContent=state.snapshot.productionGate.toUpperCase();const x=records.map(r=>[r,dp(r)]).filter(([,v])=>v!=null).sort((a,b)=>a[1]-b[1]);document.querySelector('#cheapest').textContent=x.length?`${x[0][0].country} · ${money(x[0][1])}`:'—';document.querySelector('#expensive').textContent=x.length?`${x.at(-1)[0].country} · ${money(x.at(-1)[1])}`:'—';document.querySelector('#updated').textContent=`Updated ${new Date(state.snapshot.generatedAt).toLocaleString()}`}
function ranking(records){const body=document.querySelector('#ranking');body.textContent='';records.map(r=>[r,dp(r)]).filter(([,v])=>v!=null).sort((a,b)=>a[1]-b[1]).forEach(([r,v],i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${r.country}</td><td>${money(v)}</td><td><a class="source-link" href="${r.sourceUrl}" target="_blank" rel="noopener">source ↗</a></td>`;tr.addEventListener('click',e=>{if(!e.target.closest('a'))show(r)});body.append(tr)})}
function historyChart(code,currency){const host=document.querySelector('#history-chart');host.textContent='';const pts=(state.history?.countries?.[code]||[]).filter(p=>p.currency===currency);if(pts.length<2){host.innerHTML='<p style="color:var(--muted);font-size:12px">Price history starts accumulating from the first production run.</p>';return}const W=520,H=220,m={l:44,r:12,t:12,b:28};const xs=pts.map(p=>new Date(`${p.date}T00:00:00Z`)),ys=pts.map(p=>p.pricePer330Ml);const x=d3.scaleTime().domain(d3.extent(xs)).range([m.l,W-m.r]);const y=d3.scaleLinear().domain(d3.extent(ys)).nice().range([H-m.b,m.t]);const svg=d3.select(host).append('svg').attr('viewBox',`0 0 ${W} ${H}`).style('width','100%').style('height','auto');svg.append('g').attr('transform',`translate(0,${H-m.b})`).call(d3.axisBottom(x).ticks(4).tickSizeOuter(0)).call(g=>g.selectAll('text,line,path').attr('color','#9fb0c5'));svg.append('g').attr('transform',`translate(${m.l},0)`).call(d3.axisLeft(y).ticks(5).tickSizeOuter(0)).call(g=>g.selectAll('text,line,path').attr('color','#9fb0c5'));const line=d3.line().x((d,i)=>x(xs[i])).y(d=>y(d.pricePer330Ml));svg.append('path').datum(pts).attr('fill','none').attr('stroke','currentColor').attr('stroke-width',2).attr('d',line);svg.append('text').attr('x',m.l).attr('y',11).attr('fill','#9fb0c5').attr('font-size',11).text(`330 ml equivalent · ${currency}`)}
function show(r){document.querySelector('#country-title').textContent=r.country;const st=r.stale?'stale':'fresh';document.querySelector('#country-detail').innerHTML=`<dl><dt>Status</dt><dd><span class="badge ${st}">${st.toUpperCase()}</span></dd><dt>Shelf price</dt><dd>${r.currency} ${fmt.format(r.shelfPrice)}</dd><dt>Package</dt><dd>${fmt.format(r.packageVolumeMl)} ml</dd><dt>330 ml equivalent</dt><dd>${r.currency} ${fmt.format(r.pricePer330Ml)}</dd><dt>${state.target} equivalent</dt><dd>${money(dp(r))}</dd><dt>Collection mode</dt><dd>${r.sourceMode} · HTTP ${r.httpStatus}</dd><dt>Observed price</dt><dd>${esc(r.observedPriceText||'—')}</dd><dt>Observed volume</dt><dd>${esc(r.observedVolumeText||'—')}</dd><dt>Last fresh</dt><dd>${new Date(r.lastFreshAt).toLocaleString()}</dd><dt>Source</dt><dd><a href="${r.sourceUrl}" target="_blank" rel="noopener">Open retailer ↗</a></dd></dl>`;historyChart(r.code,r.currency)}
function scale(records){const vals=records.map(dp).filter(v=>v!=null).sort((a,b)=>a-b),lo=d3.quantile(vals,.08)??0,mid=d3.quantile(vals,.5)??1,hi=d3.quantile(vals,.92)??2,s=d3.scaleLinear().domain([lo,mid,hi]).range(['#4fd1a1','#f2c94c','#ff7a7a']).clamp(true);document.querySelector('#legend').innerHTML=`<span>${money(lo)}</span><span class="legend-bar"></span><span>${money(hi)}</span>`;return s}
async function map(records){if(!state.world)state.world=await j('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json');const host=document.querySelector('#map');host.textContent='';const W=1200,H=600,fc=topojson.feature(state.world,state.world.objects.countries),proj=d3.geoNaturalEarth1().fitSize([W,H],fc),path=d3.geoPath(proj),s=scale(records),tip=document.querySelector('#tooltip'),svg=d3.select(host).append('svg').attr('viewBox',`0 0 ${W} ${H}`);svg.selectAll('path').data(fc.features).join('path').attr('d',path).attr('class',d=>{const c=numericToAlpha2.get(String(d.id).padStart(3,'0'));return state.byCode.has(c)?'country has-data':'country no-data'}).attr('fill',d=>{const c=numericToAlpha2.get(String(d.id).padStart(3,'0')),r=state.byCode.get(c),v=r?dp(r):null;return v==null?'#1c2a3b':s(v)}).on('mousemove',(e,d)=>{const c=numericToAlpha2.get(String(d.id).padStart(3,'0')),r=state.byCode.get(c);if(!r){tip.hidden=true;return}tip.hidden=false;tip.style.left=`${e.clientX+14}px`;tip.style.top=`${e.clientY+14}px`;tip.innerHTML=`<strong>${r.country}</strong>${money(dp(r))} / 330 ml`}).on('mouseleave',()=>tip.hidden=true).on('click',(_,d)=>{const r=state.byCode.get(numericToAlpha2.get(String(d.id).padStart(3,'0')));if(r)show(r)})}
async function render(){const records=state.snapshot.records.filter(r=>!r.stale);state.byCode=new Map(records.map(r=>[r.code,r]));summary(records);ranking(records);await map(records)}
async function init(){try{[state.snapshot,state.fx,state.history]=await Promise.all([j('./data/current.json'),j('./data/fx.json'),j('./data/history-summary.json')]);document.querySelector('#currency').addEventListener('change',async e=>{state.target=e.target.value;await render()});await render()}catch(e){console.error(e);document.querySelector('#updated').textContent='Data unavailable';document.querySelector('#map').innerHTML='<p style="padding:24px;color:#ff9d9d">Could not load production data.</p>'}}
init();
